apiVersion: managed.msp.sbopsv/v1alpha1
kind: UserConfig
metadata:
  name: uc
  namespace: staging
spec:
  namespaces:
    - name: namespace-sato
      create: true
  repositories:
    - name: satorepo1
      url: ssh://git@github.com:SatoRihwa/cnapVerification
      branch: test
      path: ./
