apiVersion: managed.msp.sbopsv/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: staging
spec:
  chart:
    name: rdb
    version: 0.7.x
  settings:
    databaseType: postgres
    instance:
    create: true
    name: postgres-cnap-msp2207707
    location: japaneast
    vmType: Standard_D2s_v3
    tier: GeneralPurpose
  database:
    - name: staging-db
  users:
    - name: maintainer
      secret:
        key: satotest
  azure:
    resourceGroup:
      name: managed-cluster-rg
    databaseServer:
      serverVersion: "13"
      createMode: Default
    firewallRules:
      - name: allow-azure-services
        startIpAddress: 0.0.0.0
        endIpAddress: 0.0.0.0